### ISSUE TITLE
Issue with Transport Tycoon

### ISSUE THREAD

**Issue by loki666** [sneakernets/DMXOPL#11]
Since your latest update I'm having issues with the track ttd02.mid (Little Red Diesel)

Alot of notes are cut no matter how much OPL3 core I emulate.

Your can test with the latest version of my MIDI Player (1.6.9)

https://www.transporttycoon.net/music?recording=3

**Comment by loki666** [comment]
https://www.transporttycoon.net/music?recording=1

**Comment by sneakernets** [comment]
Well that's weird stuff. The X86-64 version allows for more chips, and increasing them from 6 to something obscene like *25* removed the issue.

Notes are *sticking* somehow, and aren't being freed.

It's not just `ttd02.mid`, I'm afraid. I've run into this multiple times during development, just midis acting *very* strange in libADLMIDI. I can't figure out why.

I double-checked the patch to make sure that notes weren't staying on, and they're not.

Paging @Wohlstand !

**Comment by loki666** [comment]
mmmh in adldata.cpp i see alot of `infs` and `nans` values
any idea @wohlstand

**Comment by loki666** [comment]
there is definitely something wrong with libADLMIDI gen_adldata
I reverted the changes on my version and there is no more `infs` and `nans` values, and `ttd02.mid` is playing just fine

**Comment by Wohlstand** [comment]
Hey, I wanted to write here from phone, but seems I had bad network and message wasn't sent. I wonted to write:
Which compiler you are used?
Try to nuke cache file, recompile gen_adldata.cpp and rebuild complete from scratch.
I'll try that by myself

**Comment by loki666** [comment]
I did nuke the cache, and alot of values were different 

`gcc (GCC) 7.1.1 20170630`

**Comment by Wohlstand** [comment]
I also see that there are on different computers are different

**Comment by loki666** [comment]
closing since DMXOPL is not the issue
