### ISSUE TITLE
Contributing process

### ISSUE THREAD

**Issue by OlPainless** [sneakernets/DMXOPL#13]
Hi,

I have some patches I'd like to contribute, but I am unsure of what process is in place. That is, how should individual patches be delivered to the repo?

Br.
Andreas

**Comment by sneakernets** [comment]
If you can, submit them as `opli` format from FMBankEdit, so I can add them easily.
and add the instruments to the contributions folder.

**Comment by OlPainless** [comment]
Done and done. Thanks!
