### ISSUE TITLE
Fix snares

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/DMXOPL#16]
Lee Jackson strikes again, abusing snares. Fix snares for now until libADLMIDI handles it.

**Comment by OlPainless** [comment]
Which song causes the issue? Is it the square wave beep problem or is it something new?

**Comment by sneakernets** [comment]
it's the square wave problem. A lot of that is unavoidable due to 0,1-tick notes 9_9

**Comment by sneakernets** [comment]
Not much I can do about this, unfortunately.
