### ISSUE TITLE
Move all instruments that use high notes to 0 voice offset (if possible)

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/DMXOPL#24]
Thanks to a friend that noticed some of his midi files broke on some xylophone parts, sure enough, the top range that one would expect to play *does not play*. culprit? the one octave offset.

On some voices this is unavoidable. however, on those that can be fixed, let's fix it. Voices that are expected to play high ranges shouldn't be limited at all.

**Comment by freq-mod** [comment]
just did it dc22390

**Comment by sneakernets** [comment]
I'll take a look at that. If it didn't change the timbre of anything, we're good!

**Comment by sneakernets** [comment]
Largely done but some instruments suffer, need to survey the damage.
