### ISSUE TITLE
Replace Trumpet

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/DMXOPL#25]
While I like the patch we have, it breaks in DMX due to DMX failing so hard with AM mode (Why??!)

Likely reverting to the old patch, but maybe I don't have to (Tyrian?)

**Comment by freq-mod** [comment]
VERY quick and dirty fix: 
![zrzut ekranu z 2017-10-28 16-15-18](https://user-images.githubusercontent.com/32672779/32135196-443338e6-bbfb-11e7-8155-532346effaf1.png)

**Comment by sneakernets** [comment]
Thanks!

**Comment by sneakernets** [comment]
Fixed
