### ISSUE TITLE
How do I use this with gzdoom?

### ISSUE THREAD

**Issue by fragmental** [sneakernets/DMXOPL#3]
How do I use this with gzdoom?  Maybe I'm missing something, but I haven't been able to find clear instructions anywhere.

  I'm using gzdoom 3.1.0

**Comment by sneakernets** [comment]
1. `-file DMXOPL.WAD` or `-file GENMIDI.op2` should work.

2. In Options -> Sound Options, change "Midi Device" to "OPL Synth Emulation":

![image](https://user-images.githubusercontent.com/5595293/27556707-46d2c5ca-5a7c-11e7-93c7-babf83ca91b6.png)

3. Then Go to Advanced Options at the bottom:
![image](https://user-images.githubusercontent.com/5595293/27556737-66d6b250-5a7c-11e7-80d8-4134aa40d776.png)

4. Move the "Number of emulated OPL chips" slider to around 6. OPL Emulator Cores are in order of CPU power needed: Mame OPL2, DosBox OPL3, Java OPL3, and Nuked OPL3.

5. Go back a menu, select "Restart Sound", and press Enter. That should reset the sound with the new options.

More info here: https://zdoom.org/wiki/Advanced_sound_options

**Comment by sneakernets** [comment]
Closing. Will be adding this to the README.
