### ISSUE TITLE
Music Box and Glockenspiel need improvement

### ISSUE THREAD

**Issue by freq-mod** [sneakernets/DMXOPL#32]
Compared to SC-55 (or even that damned Microsoft GS Synth) they are totally different and hardly resemble what they're supposed to be, ESPECIALLY at lower octaves.

While I experimented with these two, I doubt I reached the optimum. Maybe I was going in the totally wrong direction ( ͡° ͜ʖ ͡°)

P.S. If you need more midis for testing purposed, I can "donate" some of mine. Downloaded them a goood while ago from an ancient japanese site, interestingly they're so good I listen to them UNIRONICALLY. Since japanese VN music from 90's was so damn complex, it's a good opportunity to test less used instruments. such as Tinkle Bell ;)

UPDATE: Msx box is done.

**Comment by sneakernets** [comment]
I'm looking into it. the music box is supposed to resemble the E-MU one, which sampled a Porter Box.

**Comment by sneakernets** [comment]
And yes those MIDIs would be awesome.

**Comment by freq-mod** [comment]
There it goes  
[testmids.zip](https://github.com/sneakernets/DMXOPL/files/1553140/testmids.zip)
(on the side note, th_musbx.mid will be especially helpful for testing music box instrument)

**Comment by sneakernets** [comment]
Thanks!

Yeah regarding some of your patches, I love them! But sometimes I immediately go "something is off here". Usually I can tweak it slightly to fix it, but the music box replacement sounded like it was a steel drum, which gets me thinking.... of what else I can replace with a few tweaks. It's not that I don't like them, I just get caught up in "oh this could work better as *x* or *y*".  That's how FM works - a lot of the instruments I created were almost by accident! Like the original Synth String 1 of DMX ended up being the basis for my Alto Sax (yep!).

All that is going to help when I make GS instrument voices! 👍

**Comment by freq-mod** [comment]
I know that! I also discover crapton of sounds by accident, no difference whether it's YM2612/YM2151 (which I'm somewhat more used to) or YMF262. Once I wanted to remake Acoustic Grand Piano, ended up with a slap bass o.O
About music box, that was quick and not so well thought attempt to make something like Roland. I didn't even bother to use other waveform than Sine. 
Glockenspiel is what took me LITERAL days  (despite still sounding veeery ugly and probably nothing like real thing)

**Comment by freq-mod** [comment]
OK F*K IT
GLOCKENSPIEL IS DONE
![glock](https://user-images.githubusercontent.com/32672779/34059946-bbc046c2-e1e1-11e7-9a06-d38b1f0fbfb7.PNG)
