### ISSUE TITLE
Replace some instruments I may have botched

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/DMXOPL#33]
I had a discussion with one of the contributors, I may be going a little too ambitious on some instruments. Not sure what to do here. We're at this point, which I guess is good...

**Comment by freq-mod** [comment]
Is it DMX only?
BTW on one MIDI, using wopl version I hear very loud, unpleasant screech (it may be related):
[kanojo wopl bug.zip](https://github.com/sneakernets/DMXOPL/files/1559696/kanojo.wopl.bug.zip)

**Comment by Wohlstand** [comment]
If you are using GS files with custom drum channels, there are will not work as I wasn't implemented SysEx to handle GS required events to take extra drum channels.

**Comment by freq-mod** [comment]
Thx @Wohlstand 
But anyway, what's really a problem? Which instruments are fucked? In which way? DMX only or both? More info would be useful, maybe I'm able to help

**Comment by sneakernets** [comment]
Well honestly I think we're hitting that point where we are just kicking around a rock. 

More specifically, A friend of mine found some MIDIs that totally ruin the guitar due to a "snap" sound in the decay. I never heard it until today, and yeah it was weird. I think we're hitting that point where trying to make it better makes it worse (which is a good thing, but at the same time, people in the FM community are going "wat r u doin STAHP!").

*Sighs*

I may need to take a break or something. I've been staring at an editor window for as long as I used to play WoW.

**Comment by sneakernets** [comment]
I hope that's okay that I take a small break for the holidays. We won a runner up in the Doomworld Cacowards, by the way.

**Comment by freq-mod** [comment]
Well, it's perfectly OK that you need a break after ALL that hard work you did in 2017. Hell - you prove to some that YMF262 can sound quite decent. Moreover, GM is frankly speaking 100% done, I can hardly come up with any improvements to it (glockenspiel, and maybe string pluck sound on a nylon guitar to better match SC55and that's it) EDIT: check out ed3cc47 sometime
So maybe it's high time to recharge batteries before GS :D

**Comment by sneakernets** [comment]
Thanks, I appreciate it. I've been working on this for 5+ years before I threw it on github and actually started to input the values I had on paper, which was a very long process.

**Comment by sneakernets** [comment]
Yeah this was addressed already. closing.
