### ISSUE TITLE
Guiro may be too bassy

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/DMXOPL#36]
Listening with a good Hi-Fi setup, the song here
https://instaud.io/private/0bea371c70161b688c67b509cdff7396aa9a0055 

Has a lot of unneeded bass in the short guiro.

**Comment by freq-mod** [comment]
Check out 640cb59 or pull request, I hope it alright now

**Comment by sneakernets** [comment]
"Fixed". The new ones sound great in a mix, but I'll keep fiddling with them.
