### ISSUE TITLE
Ride Cymbals need work

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/DMXOPL#41]
Since DMX isn't really a target anymore, Let's fix the cymbals. The hats are alright, it's the ride cymbals that are in trouble. I started work on the ride cymbal 1:
![image](https://user-images.githubusercontent.com/5595293/40313930-9cd51078-5cdc-11e8-8dda-e5655306675a.png)

This sounds much better but it's still not "perfect" in matching the SC-55. Ugh.

**Comment by freq-mod** [comment]
>help wanted
![ride](https://user-images.githubusercontent.com/32672779/40316150-abc9f9e0-5d1d-11e8-88f2-32e2d68096da.PNG)

**Comment by sneakernets** [comment]
Whoa that works great! Thank you!

**Comment by sneakernets** [comment]
I can fiddle around with that, but it sounds good so far! Better than what I had before!

**Comment by sneakernets** [comment]
Got 'em today. nailed it.
